### ISSUE TITLE
Automatically label NEW and UPDATED pages

### ISSUE THREAD

**Issue by mabijkerk** [quintel/documentation#182]
Currently, to add a NEW or UPDATED label to the documentation, this needs to be manually added in [custom.css](https://github.com/quintel/documentation/blob/master/src/css/custom.css) file. For example:

```css
/* Add "New" tag to some sidebar items. */
.menu a[href="/main/scenario-tools/slider-comparison"]:after {
  -webkit-font-smoothing: initial;
  border-radius: 4px;
  border: 1px solid #bac0d4;
  content: "New";
  color: #a0a6bb;
  font-size: 11px;
  font-weight: 400;
  height: 1rem;
  line-height: 1rem;
  margin: 0 0 0 auto;
  padding: 0 0.25rem;
  text-transform: uppercase;
}

.menu a.menu__link--active[href="/main/scenario-tools/slider-comparison"]:after {
  color: #e8eeff;
  border-color: #e8eeff;
}
```

It would be awesome if we could add a feature that automatically labels NEW and UPDATED documentation. This would then also remove the label after e.g. 2 months (or after each deploy?). Assigning @noracato but with (very) low priority.
